server:
  port: :9988
datasource:
  driverName: mysql
  uri: "root:2017@ebola@(bj-cynosdbmysql-grp-io3qyr86.sql.tencentcdb.com:27816)/db_goskeleton?charset=utf8&parseTime=True&loc=Local"
evankao:
  val: helloworld
